### ISSUE TITLE
bug: Fix CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/scrapers#12]
### current state
- There is a dummy email present under the **Enforcement** section in `CODE_OF_CONDUCT.md` for reporting any complaints.

### desired state
- There should be slack community's link instead of the email.

### screenshots
![Screenshot from 2024-06-19 23-44-33](https://github.com/LJOSC/scrapers/assets/29772969/ddee5422-74f2-48a6-bedf-1a5d610047a3)

**Comment by het4399** [comment]
Hey,
I would like to work on this!

**Comment by HarshDobariya79** [comment]
> Hey, I would like to work on this!

Thank you. I'm assigning this issue to you. Please go ahead @het4399.
