### ISSUE TITLE
feat: CodeForces Scraper

### ISSUE THREAD

**Issue by h3110Fr13nd** [LJOSC/scrapers#7]
## Tasks
- Add codeforces to Competitive Coding Platforms, 
- and include it's data and stats

**Comment by HarshDobariya79** [comment]
@h3110Fr13nd  Are you working on this task?

**Comment by h3110Fr13nd** [comment]
Yes. It's quite easy in codeforces. Probably forgot to self assign.

**Comment by HarshDobariya79** [comment]
> Yes. It's quite easy in codeforces. Probably forgot to self assign.

Thank you. Assigned you.
